# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
