# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20180227_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
